openchannel:
    marketplace-id: 5463cee5e4b042e3e26f1e41
    secret: E2lWmPmaADbXm3buLFr4vPa10FVm7M501XOtIMFjJBM
    api-url: https://sandbox-market.openchannel.io/
    api-version: v2
    developer-id: 1
spring:
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /assets/**
  http:
    multipart:
     max-file-size: 10MB
     max-request-size: 10MB
logging:
  level:
    ROOT: WARN
    io.openchannel: DEBUG
server:
  max-http-header-size: 2048000